#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

/**
 * Script to consolidate all SKILL.md files into a master SKILL.md file
 * in the repository root.
 */

function findSkillFiles(skillsDir) {
  const skills = [];
  
  try {
    const entries = fs.readdirSync(skillsDir, { withFileTypes: true });
    
    for (const entry of entries) {
      if (entry.isDirectory()) {
        const skillPath = path.join(skillsDir, entry.name, 'SKILL.md');
        
        try {
          if (fs.existsSync(skillPath)) {
            const stat = fs.statSync(skillPath);
            const content = fs.readFileSync(skillPath, 'utf-8');
            
            skills.push({
              name: entry.name,
              path: skillPath,
              content: content,
              size: stat.size
            });
          }
        } catch (error) {
          console.warn(`Warning: Could not read SKILL.md in ${entry.name}: ${error}`);
        }
      }
    }
  } catch (error) {
    console.error(`Error reading skills directory: ${error}`);
  }
  
  return skills.sort((a, b) => a.name.localeCompare(b.name));
}

function generateMasterSkillFile(skills, outputPath) {
  const timestamp = new Date().toISOString();
  
  let masterContent = `# Apex Unified Suite - Master Skills Documentation

> **Generated on:** ${timestamp}  
> **Total Skills:** ${skills.length}  
> **Total Size:** ${skills.reduce((sum, skill) => sum + skill.size, 0)} bytes

---

## Table of Contents

`;

  // Add table of contents
  skills.forEach((skill, index) => {
    masterContent += `${index + 1}. [${skill.name}](#${skill.name.toLowerCase().replace(/[^a-z0-9]/g, '-')})\n`;
  });

  masterContent += `\n---

## Skills Documentation

`;

  // Add each skill content
  skills.forEach((skill, index) => {
    masterContent += `### ${index + 1}. ${skill.name}

**Path:** \`${skill.path}\`  
**Size:** ${skill.size} bytes

---

`;

    // Add the skill content with proper markdown formatting
    const skillContent = skill.content
      .replace(/^# /gm, '#### ') // Convert h1 to h4
      .replace(/^## /gm, '##### ') // Convert h2 to h5
      .replace(/^### /gm, '###### '); // Convert h3 to h6
    
    masterContent += skillContent;
    
    masterContent += `\n---

`;
  });

  // Add footer
  masterContent += `---

## About This Document

This master skills documentation is automatically generated by the \`scripts/consolidate-skills.cjs\` script.

### Regeneration

To regenerate this file, run:

\`\`\`bash
node scripts/consolidate-skills.cjs
\`\`\`

### Structure

Each skill section includes:
- Skill name and metadata
- Original file path and size
- Full skill content with adjusted heading levels
- Separator for readability

**Note:** This is a generated file. Do not edit directly. Edit individual SKILL.md files in the \`.windsurf/skills/\` directories instead.
`;

  fs.writeFileSync(outputPath, masterContent, 'utf-8');
  console.log(`✅ Master SKILL.md generated at: ${outputPath}`);
  console.log(`📊 Consolidated ${skills.length} skills`);
}

function main() {
  const repoRoot = process.cwd();
  const skillsDir = path.join(repoRoot, '.windsurf', 'skills');
  const outputPath = path.join(repoRoot, 'SKILL.md');
  
  console.log('🔍 Finding SKILL.md files...');
  const skills = findSkillFiles(skillsDir);
  
  if (skills.length === 0) {
    console.log('❌ No SKILL.md files found');
    process.exit(1);
  }
  
  console.log(`📚 Found ${skills.length} SKILL.md files`);
  
  console.log('📝 Generating master SKILL.md...');
  generateMasterSkillFile(skills, outputPath);
  
  console.log('✨ Done!');
}

if (require.main === module) {
  main();
}

module.exports = { findSkillFiles, generateMasterSkillFile };
